# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ScopeWidget = QtWidgets.QWidget(self.centralwidget)
        self.ScopeWidget.setGeometry(QtCore.QRect(30, 20, 851, 581))
        self.ScopeWidget.setObjectName("ScopeWidget")
        self.connectUARTpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectUARTpushButton.setGeometry(QtCore.QRect(220, 620, 75, 23))
        self.connectUARTpushButton.setObjectName("connectUARTpushButton")
        self.portsList = QtWidgets.QComboBox(self.centralwidget)
        self.portsList.setGeometry(QtCore.QRect(30, 620, 181, 22))
        self.portsList.setObjectName("portsList")
        self.disconnectPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectPushButton.setGeometry(QtCore.QRect(300, 620, 75, 23))
        self.disconnectPushButton.setObjectName("disconnectPushButton")
        self.label_frequency = QtWidgets.QLabel(self.centralwidget)
        self.label_frequency.setGeometry(QtCore.QRect(790, 610, 91, 16))
        self.label_frequency.setObjectName("label_frequency")
        self.label_scale = QtWidgets.QLabel(self.centralwidget)
        self.label_scale.setGeometry(QtCore.QRect(790, 630, 91, 16))
        self.label_scale.setObjectName("label_scale")
        self.label_fft = QtWidgets.QLabel(self.centralwidget)
        self.label_fft.setGeometry(QtCore.QRect(410, 620, 47, 13))
        self.label_fft.setObjectName("label_fft")
        MainWindow.setCentralWidget(self.centralwidget)

        self.connectUARTpushButton.clicked.connect(self.connectUARTpushButton_clicked)
        self.disconnectPushButton.clicked.connect(self.disconnectPushButton_clicked)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectUARTpushButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectPushButton.setText(_translate("MainWindow", "Disconnect"))
        self.label_frequency.setText(_translate("MainWindow", "N/A"))
        self.label_scale.setText(_translate("MainWindow", "N/A"))
        self.label_fft.setText(_translate("MainWindow", "N/A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
